// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq_HgjZNoEKapP1ZTM7riIwXM7A3QlwtY',
    appId: '1:686668972847:web:bd2dcfcb3fef252dee57da',
    messagingSenderId: '686668972847',
    projectId: 'baat-d808f',
    authDomain: 'baat-d808f.firebaseapp.com',
    storageBucket: 'baat-d808f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD3SafR1x4Neb4KoWgCtN_nq3hQj-UbE8',
    appId: '1:686668972847:android:9f6481358c5b454bee57da',
    messagingSenderId: '686668972847',
    projectId: 'baat-d808f',
    storageBucket: 'baat-d808f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7QI7cyiSO_edd4bZWsAeAhGDTCt249N8',
    appId: '1:686668972847:ios:a27e38702fc1f1c0ee57da',
    messagingSenderId: '686668972847',
    projectId: 'baat-d808f',
    storageBucket: 'baat-d808f.appspot.com',
    iosClientId: '686668972847-g899elcd4d8u8smj9079vbehhlm8fuut.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7QI7cyiSO_edd4bZWsAeAhGDTCt249N8',
    appId: '1:686668972847:ios:df64d85dae71e40dee57da',
    messagingSenderId: '686668972847',
    projectId: 'baat-d808f',
    storageBucket: 'baat-d808f.appspot.com',
    iosClientId: '686668972847-ersfkii6iabnv5u9vkepoh6fokbkjarb.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopnow.RunnerTests',
  );
}
